### ISSUE TITLE
Intro Text for Data Cleaning Page

### ISSUE THREAD

**Issue by danmcduff** [allenai/fm-cheatsheet#18]
**Replace** 

Data cleaning and filtering are crucial steps in curating a dataset. They remove unwanted data, improving training efficiency and ensuring desirable properties like high information content, desired languages, low toxicity, and minimal personally identifiable information. Consider trade-offs when using filters and understand the importance of data mixing in preparation.

**With**

Data quality is crucial. Filtering can remove unwanted data, improving training efficiency and ensuring desirable properties like high information content, desired languages, low toxicity, and minimal personally identifiable information. Consider trade-offs when using filters and understand the importance of data mixtures.

**Comment by neural-loop** [comment]
https://onm-demo.aimodels.org/foundation-model-resources/data-cleaning-filtering-mixing/
