### ISSUE TITLE
Intro Text for Data Decontamination Page

### ISSUE THREAD

**Issue by danmcduff** [allenai/fm-cheatsheet#20]
**Replace**

Data decontamination is the process of removing evaluation data from the training dataset. This important step in data preprocessing ensures the integrity of model evaluation, ensuring that metrics are reliable and not misleading. The following resources aid in proactively protecting test data with canaries, decontaminating data before training, and identifying or proving what data a model was trained on.

**With**

Data decontamination is the process of removing evaluation data from the training set. This step ensures the integrity of model evaluation. The following resources aid in proactively protecting test data with canaries, decontaminating data before training, and identifying or proving what data a model was trained on.

**Comment by neural-loop** [comment]
https://onm-demo.aimodels.org/foundation-model-resources/data-decontamination/
