### ISSUE TITLE
Intro Text for Data Auditing Page

### ISSUE THREAD

**Issue by danmcduff** [allenai/fm-cheatsheet#21]
**Replace**

Auditing datasets is an essential component of dataset design. Spend a substantial amount of time reading through your dataset, ideally at many stages of the dataset design process. Many datasets have problems specifically because the authors did not do sufficient auditing before releasing them. Use systematic studies of the process in addition to data search, analysis, & exploration tools to track the dataset's evolution.

**With**

Auditing datasets is essential, spend a substantial amount of time inspecting your dataset at multiple stages of the dataset design process. Many datasets have problems specifically because the authors did not do sufficient auditing before releasing them. Use systematic studies of the process in addition to data search, analysis, & exploration tools to track the dataset's evolution.

**Comment by neural-loop** [comment]
https://onm-demo.aimodels.org/foundation-model-resources/data-auditing/
