### ISSUE TITLE
Intro Text for Data Documentation Page

### ISSUE THREAD

**Issue by danmcduff** [allenai/fm-cheatsheet#22]
**Replace**

When releasing new data resources with a model, it is important to thoroughly document the data. Documentation allows users to understand its intended uses, legal restrictions, attribution, relevant contents, privacy concerns, and other limitations. Many data documentation standards have been proposed, but their adoption has been uneven. Crowdsourced documentation may contain errors and omissions

**With** 

Data documentation allows users to understand their intended uses, legal restrictions, attribution, relevant contents, privacy concerns, and other limitations. Many data documentation standards have been proposed, but their adoption has been uneven. It is important to recognize that crowdsourced documentation may contain errors and omissions.

**Comment by neural-loop** [comment]
https://onm-demo.aimodels.org/foundation-model-resources/data-documentation/
