### ISSUE TITLE
Intro Text for Finetuning Repositories

### ISSUE THREAD

**Issue by danmcduff** [allenai/fm-cheatsheet#24]
**Replace**

Fine-tuning, or other types of adaptation performed on foundation models after pretraining, are an equally important and complex step in model development. Fine-tuned models are more frequently deployed than base models. Here, we also link to some useful and widely-used resources for adapting foundation models or otherwise fine-tuning them.

**With**

Finetuning or adaptation of foundation models is a complex step in model development. These models are more frequently deployed than base models. Here, we link to some useful and widely-used resources for finetuning.

**Comment by neural-loop** [comment]
https://onm-demo.aimodels.org/foundation-model-resources/model-training-finetuning-repositories/
