### ISSUE TITLE
Intro Text for Efficiency and Resource Allocation Page

### ISSUE THREAD

**Issue by danmcduff** [allenai/fm-cheatsheet#25]
**Replace**

Knowledge of training best practices and efficiency techniques can reduce costs to train a desired model significantly. Here, we include a select few readings and resources on effectively using a given resource budget for model training, such as several canonical papers on fitting scaling laws.

**With** 

Knowledge of training best practices can reduce the cost of training a desired model significantly. Here, we link to readings and resources on effectively using a given resource budget for model training, including canonical papers on fitting scaling laws.

**Comment by neural-loop** [comment]
https://onm-demo.aimodels.org/foundation-model-resources/model-training-efficiency-resource-allocation/
