### ISSUE TITLE
Intro Text for Education Resources Page

### ISSUE THREAD

**Issue by danmcduff** [allenai/fm-cheatsheet#26]
1. Change subtitle to:  "Additional Educational Resources"

2.

**Replace**

Training models at any scale can be quite daunting to newer practitioners. Here, we include several educational resources that may be useful in learning about the considerations required for successfully and effectively training or fine-tuning foundation models.

**With** 

Training models at any scale can be quite daunting to newer practitioners. The following educational resources may be useful in learning about the considerations required for successfully and effectively training or fine-tuning foundation models.

**Comment by neural-loop** [comment]
https://onm-demo.aimodels.org/foundation-model-resources/model-training-educational-resources/
