### ISSUE TITLE
Intro Text for Environmental Impact Page

### ISSUE THREAD

**Issue by danmcduff** [allenai/fm-cheatsheet#27]
**Replace**

Current tools focus on measuring the energy consumed during training or inference and multiplying it by the carbon intensity of the energy source used. For efficient use of resources, several decisions made during or prior to model training can have significant impacts on the upstream and downstream environmental impact of a given model.

**With** 

Foundation model development is often resource intensive. The following tools help one to measure energy consumption and estimate the carbon intensity of the energy source used. Decisions made during or prior to model training can have a significant effect on the upstream and downstream environmental impact of a given model.

**Comment by neural-loop** [comment]
https://onm-demo.aimodels.org/foundation-model-resources/environmental-impact/
