### ISSUE TITLE
Intro Text for Risks and Harms Taxonomy Page

### ISSUE THREAD

**Issue by danmcduff** [allenai/fm-cheatsheet#29]
**Replace**

Taxonomies provide a way of categorising, defining and understanding risks and hazards created through the use and deployment of AI systems. Some taxonomies focus primarily on the types of interactions and uses that create a risk of harm whereas others focus on the negative effects that they lead to.

**With** 

Taxonomies provide a way of categorising, defining and understanding risks and hazards created through the use and deployment of AI systems. The following taxonomies focus on the types of interactions and uses that create a risk of harm as well as the negative effects that they lead to.

**Comment by neural-loop** [comment]
https://onm-demo.aimodels.org/foundation-model-resources/model-evaluation-risks-harms-taxonomies/
