### ISSUE TITLE
Intro Text for Risk and Harm Evaluation Page

### ISSUE THREAD

**Issue by danmcduff** [allenai/fm-cheatsheet#30]
1. Change the link text on the homepage from "Risks and Harms" to "Risks and Harms Evaluation"

2.
**Replace**

Evaluations of risk serve multiple purposes: to identify if there are issues which need mitigation, to track the success of any such mitigations, to document for other users of the model what risks are still present, and to help make decisions related to model access and release.

**With** 

The following tools for evaluating risk serve multiple purposes: to identify if there are issues which need mitigation, to track the success of any such mitigations, to document for other users of the model what risks are still present, and to help make decisions related to model access and release.

**Comment by neural-loop** [comment]
https://onm-demo.aimodels.org/foundation-model-resources/model-evaluation-risks-harms/
