### ISSUE TITLE
Intro Text for Model Documentation Page

### ISSUE THREAD

**Issue by danmcduff** [allenai/fm-cheatsheet#31]
**Replace** 

It is important to document models that are used and released. Even models and code released openly are important to document thoroughly, in order to specify how to use the model, recommended and non-recommended use cases, potential harms, state or justify decisions made during training, and more.

**With**

It is important to document models that are used and released. Even models and code released openly are important to document thoroughly, in order to specify how to use the model, recommended and non-recommended use cases, potential harms, state or justify decisions made during training, and more. The following tools can help with documentation.

**Comment by neural-loop** [comment]
https://onm-demo.aimodels.org/foundation-model-resources/model-documentation/
