### ISSUE TITLE
Intro Text for License Selection

### ISSUE THREAD

**Issue by danmcduff** [allenai/fm-cheatsheet#33]
**Replace**

Foundation models, like software, are accompanied by licenses that determine how they may be distributed, used, and repurposed. There are a variety of licenses to choose between for open foundation model developers, presenting potential challenges for new developers.

**With** 

Foundation models, like software, are accompanied by licenses that determine how they may be distributed, used, and repurposed. The following resources can help one determine which type of license to use.

**Comment by neural-loop** [comment]
https://onm-demo.aimodels.org/foundation-model-resources/license-selection/
