### ISSUE TITLE
Intro Text for Usage Monitoring Page

### ISSUE THREAD

**Issue by danmcduff** [allenai/fm-cheatsheet#34]
**Replace**

Some open foundation model developers attempt to monitor the usage of their models, whether by watermarking model outputs or gating access to the model.

**With** 

Monitoring foundation model usage is an evolving area of research. The following techniques, such as watermarking model outputs or gating access to the model, are some of the ways to do so.

**Comment by neural-loop** [comment]
https://onm-demo.aimodels.org/foundation-model-resources/usage-monitoring/
